# Generated by Django 5.2.17 on 2026-08-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aptitudequestion',
            options={'verbose_name_plural': 'Aptitude Questions'},
        ),
        migrations.AlterModelOptions(
            name='interestquestion',
            options={'verbose_name_plural': 'Interest Questions'},
        ),
        migrations.AlterModelOptions(
            name='programcriteria',
            options={'verbose_name_plural': 'Program Criteria'},
        ),
        migrations.AlterModelOptions(
            name='scoreinterpretation',
            options={'verbose_name_plural': 'Score Interpretations'},
        ),
    ]
