# Generated by Django 5.2.17 on 2026-08-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0002_alter_aptitudequestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptitudequestion',
            name='dimension',
            field=models.CharField(choices=[('Numerical Reasoning', 'Numerical Reasoning'), ('Deductive Reasoning', 'Deductive Reasoning'), ('Inductive Reasoning', 'Inductive Reasoning'), ('Problem Sensitivity', 'Problem Sensitivity'), ('Visualization', 'Visualization'), ('Information Ordering', 'Information Ordering'), ('Oral Comprehension', 'Oral Comprehension'), ('Oral Expression', 'Oral Expression'), ('Originality', 'Originality')], max_length=100),
        ),
    ]
