# Generated by Django 5.2.17 on 2026-08-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0003_alter_aptitudequestion_dimension'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitudequestion',
            name='for_validation',
            field=models.BooleanField(default=True),
        ),
    ]
