# Generated by Django 5.2.17 on 2026-08-19 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0004_aptitudequestion_for_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptitudequestion',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Correct Answer'),
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='dimension',
            field=models.CharField(choices=[('Numerical Reasoning', 'Numerical Reasoning'), ('Deductive Reasoning', 'Deductive Reasoning'), ('Inductive Reasoning', 'Inductive Reasoning'), ('Problem Sensitivity', 'Problem Sensitivity'), ('Visualization', 'Visualization'), ('Information Ordering', 'Information Ordering'), ('Oral Comprehension', 'Oral Comprehension'), ('Oral Expression', 'Oral Expression'), ('Originality', 'Originality')], max_length=100, verbose_name='Dimension'),
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='for_validation',
            field=models.BooleanField(default=True, verbose_name='For Validation'),
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='option_a',
            field=models.CharField(max_length=255, verbose_name='Option A'),
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='option_b',
            field=models.CharField(max_length=255, verbose_name='Option B'),
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='option_c',
            field=models.CharField(max_length=255, verbose_name='Option C'),
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='option_d',
            field=models.CharField(max_length=255, verbose_name='Option D'),
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='question_text',
            field=models.TextField(verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='interestquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='interestquestion',
            name='item_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Item Number'),
        ),
        migrations.AlterField(
            model_name='interestquestion',
            name='question_text',
            field=models.TextField(verbose_name='Question Text'),
        ),
        migrations.AlterField(
            model_name='interestquestion',
            name='riasec_area',
            field=models.CharField(choices=[('R', 'Realistic'), ('I', 'Investigative'), ('A', 'Artistic'), ('S', 'Social'), ('E', 'Enterprising'), ('C', 'Conventional')], max_length=1, verbose_name='RIASEC Area'),
        ),
        migrations.AlterField(
            model_name='interestquestion',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='programcriteria',
            name='criterion_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Criterion ID'),
        ),
        migrations.AlterField(
            model_name='programcriteria',
            name='dimension_name',
            field=models.CharField(max_length=100, verbose_name='Dimension Name'),
        ),
        migrations.AlterField(
            model_name='programcriteria',
            name='minimum_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Minimum Level'),
        ),
        migrations.AlterField(
            model_name='programcriteria',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='customization.program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='programcriteria',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='condition_expression',
            field=models.TextField(verbose_name='Condition Expression'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='explanation_template',
            field=models.TextField(verbose_name='Explanation Template'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='customization.program', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='rule_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Rule ID'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='score_adjustment',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score Adjustment'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='scoreinterpretation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='scoreinterpretation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='scoreinterpretation',
            name='label',
            field=models.CharField(max_length=50, unique=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='scoreinterpretation',
            name='max_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Maximum Score'),
        ),
        migrations.AlterField(
            model_name='scoreinterpretation',
            name='min_score',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Minimum Score'),
        ),
        migrations.AlterField(
            model_name='scoreinterpretation',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
    ]
