# Generated by Django 5.2.17 on 2026-08-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0005_alter_aptitudequestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptitudequestion',
            name='for_validation',
            field=models.BooleanField(default=True, verbose_name='For Validation?'),
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Active?'),
        ),
    ]
