# Generated by Django 5.2.17 on 2026-08-22 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0006_alter_aptitudequestion_for_validation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Log ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User Logged In'), ('LOGOUT', 'User Logged Out'), ('ASSESSMENT_COMPLETED', 'Assessment Completed')], max_length=64, verbose_name='Action')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
