# Generated by Django 5.2.17 on 2026-08-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0007_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Logged In'), ('LOGOUT', 'User Logged Out'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('FAILED_PASSWORD_RESET', 'Failed Password Reset'), ('ASSESSMENT_COMPLETED', 'Assessment Completed')], max_length=64, verbose_name='Action'),
        ),
    ]
