# Generated by Django 5.2.17 on 2026-08-18 00:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('last_date_taken', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentInterestResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customization.interestquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_responses', to='assessment.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAptitudeResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customization.aptitudequestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aptitude_responses', to='assessment.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('aptitude_scores_json', models.JSONField()),
                ('r_score', models.PositiveIntegerField()),
                ('i_score', models.PositiveIntegerField()),
                ('a_score', models.PositiveIntegerField()),
                ('s_score', models.PositiveIntegerField()),
                ('e_score', models.PositiveIntegerField()),
                ('c_score', models.PositiveIntegerField()),
                ('riasec_code', models.CharField(max_length=10)),
                ('alignment_level', models.CharField(max_length=50)),
                ('generated_explanation', models.TextField()),
                ('date_generated', models.DateTimeField(auto_now=True)),
                ('second_recommended_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_recommendations', to='customization.program')),
                ('third_recommended_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_recommendations', to='customization.program')),
                ('top_recommended_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_recommendations', to='customization.program')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_result', to='assessment.studentprofile')),
            ],
        ),
    ]
