# Generated by Django 5.2.17 on 2026-08-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
