# Generated by Django 5.2.17 on 2026-08-19 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_studentprofile_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentresult',
            options={'verbose_name_plural': 'Assessment Results'},
        ),
        migrations.AlterModelOptions(
            name='studentaptituderesponse',
            options={'verbose_name_plural': 'Student Aptitude Responses'},
        ),
        migrations.AlterModelOptions(
            name='studentinterestresponse',
            options={'verbose_name_plural': 'Student Interest Responses'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AlterUniqueTogether(
            name='studentprofile',
            unique_together={('full_name', 'student_id')},
        ),
    ]
