# Generated by Django 5.2.17 on 2026-08-19 22:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_assessmentresult_options_and_more'),
        ('customization', '0005_alter_aptitudequestion_correct_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresult',
            name='a_score',
            field=models.PositiveIntegerField(verbose_name='A Score'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='alignment_level',
            field=models.CharField(max_length=50, verbose_name='Alignment Level'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='aptitude_scores_json',
            field=models.JSONField(verbose_name='Aptitude Scores'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='c_score',
            field=models.PositiveIntegerField(verbose_name='C Score'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='date_generated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Generated'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='e_score',
            field=models.PositiveIntegerField(verbose_name='E Score'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='generated_explanation',
            field=models.TextField(verbose_name='Generated Explanation'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='i_score',
            field=models.PositiveIntegerField(verbose_name='I Score'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='r_score',
            field=models.PositiveIntegerField(verbose_name='R Score'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='result_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Result ID'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='riasec_code',
            field=models.CharField(max_length=10, verbose_name='RIASEC Code'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='s_score',
            field=models.PositiveIntegerField(verbose_name='S Score'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='second_recommended_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_recommendations', to='customization.program', verbose_name='Second Recommended Program'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_result', to='assessment.studentprofile', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='third_recommended_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_recommendations', to='customization.program', verbose_name='Third Recommended Program'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='top_recommended_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_recommendations', to='customization.program', verbose_name='Top Recommended Program'),
        ),
        migrations.AlterField(
            model_name='studentaptituderesponse',
            name='is_correct',
            field=models.BooleanField(verbose_name='Correct?'),
        ),
        migrations.AlterField(
            model_name='studentaptituderesponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customization.aptitudequestion', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='studentaptituderesponse',
            name='response_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Response ID'),
        ),
        migrations.AlterField(
            model_name='studentaptituderesponse',
            name='selected_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Selected Answer'),
        ),
        migrations.AlterField(
            model_name='studentaptituderesponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aptitude_responses', to='assessment.studentprofile', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='studentinterestresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customization.interestquestion', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='studentinterestresponse',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='studentinterestresponse',
            name='response_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Response ID'),
        ),
        migrations.AlterField(
            model_name='studentinterestresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_responses', to='assessment.studentprofile', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='last_date_taken',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Date Taken'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sex',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
