# Generated by Django 5.2.17 on 2026-08-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_assessmentresult_a_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Security Answer'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='security_question',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Security Question'),
        ),
    ]
